services:
  db:
    image: mariadb:11.3.2-jammy
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: root_db
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - mynetwork

  php-app:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:80"
    networks:
      - mynetwork

networks:
  mynetwork:
